### ISSUE TITLE
Error from sample-ethereum-tx-tracker

### ISSUE THREAD

**Issue by toshiboy86** [HAECHI-LABS/henesis-sdk-js#47]
Following the step mentioned
https://docs.henesis.io/transaction-tracker/tutorial-tx-tracker#step-by-step

and when I run the code `node index.js` , this error comes out 

```
> node index.js
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module '/Users/user/Workspace/Henesis/sample-ethereum-tx-tracker/index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```
MacOS Mojave: 10.14.4
Node version is `v12.14.0`

**Comment by jasonkim-tech** [comment]
Thank you for reporting the problem.
I checked that the command is invalid.
I have modified the documentation to match the latest sample code.
Please run `node example.js`  instead of `node index.js`

Docs updated: https://docs.henesis.io/transaction-tracker/tutorial-tx-tracker

**Comment by jasonkim-tech** [comment]
Did you have an account? 
If you want to use Henesis, you have to need an account.

**Comment by toshiboy86** [comment]
Updated code works. Thanks for your rapid update!

> Did you have an account?
Yes I've already got one.
